### ISSUE TITLE
Install.sh does not seem to install correctly (Ubuntu 15.10)

### ISSUE THREAD

**Issue by MichaelAquilina** [mmstick/systemd-manager#12]
These are the steps I took:

```
git clone https://github.com/mmstick/systemd-manager
cd systemd-manager
./install.sh
```

which *seems* to install. But when trying to open systemd-manager nothing happens. Could you advise me where to get appropriate logs from?

**Comment by mmstick** [comment]
How are you opening systemd-manager? `systemd-manager-pkexec` is the file you want to open, which is what the desktop shortcut points to.

**Comment by MichaelAquilina** [comment]
Well then. This might explain it?

```
systemd-manager-pkexec 
Error accessing /usr/bin/systemd-manager: No such file or directory
```

**Comment by mmstick** [comment]
Do you have any build issues with `cargo build --release`?

**Comment by MichaelAquilina** [comment]
Ah. I dont have cargo installed. I wrongly assumed that `install.sh` does not need it once it completed without issue.

**Comment by MichaelAquilina** [comment]
I'll close off the issue as it obviously not really an issue.
