### ISSUE TITLE
Window Buttons are Centered

### ISSUE THREAD

**Issue by RichardlL** [mmstick/systemd-manager#17]
![screenshot from 2016-05-20 15-28-33](https://cloud.githubusercontent.com/assets/6051772/15439697/c09319ec-1e9f-11e6-9e0b-ed2ab59fed94.png)

I'm using Ubuntu 16.04 with Numix GTK theme.

Fresh Build off master.

I'll try to do some twiddling

Edit: Same with adiwata

**Comment by mmstick** [comment]
Seems to be a common bug on Ubuntu with GTK3 CSD applications. I suspect that Canonical is patching their software in such a way that it breaks the HeaderBar for unmodified GTK3 software. The left headerbar shouldn't even have a window control because it's disabled. If you set your window controls to the right it looks as intended.

**Comment by daboross** [comment]
I'm betting this is because of the window icons being set to appear on the left, as on Gentoo I also experience this. Ubuntu does set icons to appear on the left by default, but with that setting in my environment this also occurs

**Comment by mmstick** [comment]
@daboross Do you also experience the same behaviour with GNOME Tweak Tool?

**Comment by daboross** [comment]
@mmstick I'll check when I get home, but I don't *think* so. I haven't used gnome tweak tool in a while, and this isn't really a large issue for me, but I think this is the first application it's happened in.

**Comment by mmstick** [comment]
I will have a fix uploaded soon.

**Comment by mmstick** [comment]
See if [this patch](https://github.com/mmstick/systemd-manager/commit/464ef47e20a9966867c51a1c561fb0ad8bb67366) fixes the problem for you.

**Comment by RichardlL** [comment]
Looking good to me.

Thanks for the attention to detail! Great project!

![image](https://cloud.githubusercontent.com/assets/6051772/15634464/3b4abe30-2592-11e6-8ebc-67a7bcd0bd82.png)

**Comment by daboross** [comment]
Works great, thank you! This is a pretty awesome project.
