### ISSUE TITLE
[Info Request] systemd-manager + systemd on Ubuntu from PPA

### ISSUE THREAD

**Issue by glitsj16** [mmstick/systemd-manager#20]
Hi, I've recently been following the git commits and am testing your systemd-manager GUI with great interest. On Arch Linux, everything works just fine. As I also use Ubuntu (16.04) on some machines, I tried to get it working there as well. Mixed results, untill I realized I had https://launchpad.net/~pitti/+archive/ubuntu/systemd active on my machines. As soon as I purged that, systemd-manager started to work as expected. I've contacted the PPA maintainer about this, requesting if he would be interested in looking into why systemd-manager errors-out with the systemd version from his PPA. Alas this is by e-mail and I haven't a URL to supply here. As soon as I get a response, I'll add it to the issue.

I do realize this might not be of interest to you. Enough on one's plate already etc. So this isn't a bug report, rather a request for info/thoughts on the issue at hand, as detailed in the output of relevant commands below. Thoughts?

Thanks for reading this,

glitsj16

= = = info (snippets) = = =

$ lsb_release -d
Description:	Ubuntu 16.04 LTS

### scenario 1 :: without systemd PPA ###
$ apt-cache policy systemd
systemd:
  Installed: 229-4ubuntu6
  Candidate: 229-4ubuntu6
  Version table:
 *** 229-4ubuntu6 500
        500 http://archive.ubuntu.com/ubuntu xenial-updates/main amd64 Packages
        100 /var/lib/dpkg/status
     229-4ubuntu4 500
        500 http://archive.ubuntu.com/ubuntu xenial/main amd64 Packages

$ systemd-manager-pkexec
--> starts cleanly, works as expected

### scenario 2 :: with systemd PPA ###
#+ https://launchpad.net/~pitti/+archive/ubuntu/systemd

$ sudo add-apt-repository ppa:pitti/systemd
$ sudo apt-get update && sudo apt-get -y update
...

$ apt-cache policy systemd
systemd:
  Installed: 230+upstream20160523-0.master
  Candidate: 230+upstream20160523-0.master
  Version table:
 *** 230+upstream20160523-0.master 500
        500 http://ppa.launchpad.net/pitti/systemd/ubuntu xenial/main amd64 Packages
        100 /var/lib/dpkg/status
     229-4ubuntu6 500
        500 http://archive.ubuntu.com/ubuntu xenial-updates/main amd64 Packages
     229-4ubuntu4 500
        500 http://archive.ubuntu.com/ubuntu xenial/main amd64 Packages

#+ 2.1 :: no reboot after upgrading systemd from PPA
$ systemd-manager-pkexec
thread '<main>' panicked at 'Unknown Type: /run/systemd/generator/dev-disk-by\\x2duuid-05839743\\x2d3b4e\\x2d4eab\\x2d8408\\x2dbab5cef3c4fe.swap', src/systemd/mod.rs:31

#+ 2.2 :: after upgrading systemd from PPA + reboot:
$ systemd-manager-pkexec
thread '<main>' panicked at 'Unknown State:  Str("generated")])', src/systemd/mod.rs:51

**Comment by mmstick** [comment]
I have all the Unit Types implemented [here](https://github.com/mmstick/systemd-manager/blob/master/src/systemd/mod.rs#L16:L34). It's designed to panic when an unknown type is detected. This is the first I've seen a swap unit type before. I'll add it to the list.

**Comment by mmstick** [comment]
It should be fixed now with [this patch](https://github.com/mmstick/systemd-manager/commit/17cc6d11e18478b2e928dd4c243f8382edd815ad).

**Comment by glitsj16** [comment]
Confirming the patch solved the issue as described under 'scenario 2.1'. Thanks you for working this in so fast & knowledgeable. I've copycatted your patch and did some more testing with scenario 2.2. After using the below patch I can know use systemd-manager without problems/errors, although I have no clue what it means, dumb luck I guess... Here's what I did, maybe it helps you in some way.

--- a/src/systemd/mod.rs
+++ b/src/systemd/mod.rs
@@ -35,7 +35,7 @@
 }
 
 #[derive(Clone, Debug, PartialEq, Eq)]
-pub enum UnitState { Bad, Disabled, Enabled, Indirect, Linked, Masked, Static }
+pub enum UnitState { Bad, Disabled, Enabled, Generated, Indirect, Linked, Masked, Static, Transient }
 impl UnitState {
     /// Takes the string containing the state information from the dbus message and converts it
     /// into a UnitType by matching the first character.
@@ -49,6 +49,8 @@
             'l' => UnitState::Linked,
             'm' => UnitState::Masked,
             'b' => UnitState::Bad,
+            'g' => UnitState::Generated,
+            't' => UnitState::Transient,
             _   => panic!("Unknown State: {}", x),
         }
     }

I'll do some more testing on this, diffing changes introduced between systemd v229 & v230 as is available in the Ubuntu PPA. Please feel free to close this issue whenever you feel it satisfies your needs for this great GUI.

Cheers

**Comment by mmstick** [comment]
Thanks for reporting the new states/types ahead of time. I have now added the two states with [this patch](https://github.com/mmstick/systemd-manager/commit/e47f5c5c80b59b9f17e7b3843d024f01af4cb46e). Arch Linux is still using systemd 229, which is what I'm using.

I don't, as of yet, actually use all these other types, but for the sake of completeness I think it's a good idea to ensure that the application collects that information properly, even if it does nothing with those states and types. The application mainly aims to be simplistic in only displaying the units that matter to the user -- units that can be enabled, disabled, stopped and started.
