### ISSUE TITLE
Missing unit files from /etc/systemd

### ISSUE THREAD

**Issue by celilo** [mmstick/systemd-manager#22]
Systemd allows for units to be overridden by placing a customized copy in /etc/systemd/system. When overrides exist in /etc/systemd/system, the override units are not included in systemd manager. If an override unit is removed, the default unit does appear upon restart of systemd manager.

**Comment by mmstick** [comment]
Do you have any example unit files to test with? The program does not look through the filesystem for units but gets a complete list of them through systemd's `ListUnitFiles

**Comment by celilo** [comment]
Based on the fact that you are utilizing `systemctl list-unit-files` to populate the unit list, it surprises me that my custom unit is not listed in systemd manager because my custom unit is displayed when I execute either of the following commands rom a terminal: 
```
systemctl list-unit-files
systemctl list-units --type=service --all
```
I wonder if this is a bug in your linux distro?

The specific unit that brought my attention to the issue is `/etc/systemd/system/hiawatha.service` which overrides `/usr/lib/systemd/system/hiawatha.service` and contains the following:
```
[Unit]
Description=Hiawatha Web Server
After=network.target remote-fs.target nss-lookup.target

[Service]
Type=simple
SyslogIdentifier=hiawatha
ExecStartPre=/usr/bin/hiawatha -k ; /usr/bin/wigwam
ExecStart= /usr/bin/hiawatha -d
TimeoutSec=10
#(doesn't like this setting. Can't find files) PrivateTmp=true
LimitNOFILE=infinity
#CapabilityBoundingSet=CAP_NET_BIND_SERVICE CAP_CHOWN CAP_DAC_OVERRIDE CAP_FOWNER CAP_FSETID CAP_SETGID CAP_SETUID

[Install]
WantedBy=multi-user.target
```
If I run systemctl list-unit-files from a terminal the list includes hiawatha.service, but it does not appear in SystemD Manager. If I remove the custom unit `/etc/systemd/system/hiawatha.service`, the default unit `/usr/lib/systemd/system/hiawatha.service` is displayed.

However, the issue has nothing to do with the unit. If I simply copy `/usr/lib/systemd/system/libvirtd.service` to `/etc/systemd/system/libvirtd.service`, run `systemctl daemon-reload`, and then restart systemd manager, libvirtd.service also disappears from the list. Thus you should be able to test this this by doing the same with any unit file.

**Comment by celilo** [comment]
After replying, I noticed that you were using the dbus api to issue the listunitfiles command while I used the command line utility to get my results. I issued the following dbus command from a terminal and my custom unit was returned in the resultant array consistent with the other methodology.
 `gdbus call -m org.freedesktop.systemd1.Manager.ListUnitFiles --system --dest org.freedesktop.systemd1 --object-path /org/freedesktop/systemd1`

From the result: `('/etc/systemd/system/hiawatha.service', 'enabled')`

I don't speak rust, but after a brief look at your code, I think that the issue may be exclusion of /etc at line 133 of dbus.rs

**Comment by mmstick** [comment]
See if [this patch](https://github.com/mmstick/systemd-manager/commit/a87e03c167e76ced97217b5fcb4aa1a6f0a86786) fixes it.

**Comment by celilo** [comment]
The units within /etc are now included. I did notice that the custom units sort to the top. Neither right or wrong, but just wanted to point it out so that you can achieve whatever behaviour you desire.

My custom sockets are also listed with the same sorting to the top as the service units.

Call it fixed. Thanks

**Comment by mmstick** [comment]
It should be sorted by name rather than path now.
