### ISSUE TITLE
Out of Sync Journal tab

### ISSUE THREAD

**Issue by celilo** [mmstick/systemd-manager#23]
After starting or stopping a service the journal tab does not reflect activity until the user selects a different unit is and returns to the previous journal tab.

**Comment by mmstick** [comment]
That's generally what the refresh button is for.

**Comment by mmstick** [comment]
Regardless, [this patch](https://github.com/mmstick/systemd-manager/commit/0aa9eebffb86c6ba5f5f4996f43fee3f4447f574) will allow the start and stop buttons to also refresh the journal.

**Comment by celilo** [comment]
Thanks. I missed the refresh dialog at the bottom of my screen, though I believe that your patch provides a more intuitive behaviour.
