### ISSUE TITLE
Propose adding cargo to Makefile

### ISSUE THREAD

**Issue by linuxlite** [mmstick/systemd-manager#25]
```
jerry@jerry-vb-32:~/systemd-manager$ make ubuntu
sudo apt install libgtk-3-dev
[sudo] password for jerry: 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
libgtk-3-dev is already the newest version (3.18.9-1ubuntu3).
0 upgraded, 0 newly installed, 0 to remove and 3 not upgraded.
cargo build --release
make: cargo: Command not found
Makefile:22: recipe for target 'ubuntu' failed
make: *** [ubuntu] Error 127
jerry@jerry-vb-32:~/systemd-manager$ cargo build --release
The program 'cargo' is currently not installed. You can install it by typing:
sudo apt install cargo
jerry@jerry-vb-32:~/systemd-manager$
```

**Comment by mmstick** [comment]
Does it build with the version of rustc in Ubuntu 16.04's software repository? It's generally best just to use the official [rustup toolchain manager](https://www.rustup.rs/).

**Comment by linuxlite** [comment]
I've been using the curl link in https://www.rustup.rs/ for all the builds to date.

**Comment by linuxlite** [comment]
I removed the cargo Ubuntu package from my system, then built a systemd-manager package successfully with the latest commit. Build successful. Thank you Michael.

**Comment by mmstick** [comment]
Generally, I cannot guarantee that the bundled version of cargo/rustc will be able to compile the project. It would be nice if the Debian community would package `rustup` instead of `cargo` much as the Arch community [has done](https://aur.archlinux.org/packages/rustup/). Then I wouldn't have to direct people to use that precise curl link.

**Comment by linuxlite** [comment]
With more time and adoption, I'm hopeful someone will do that. I would volunteer, but have plenty on my plate as it is.
