### ISSUE TITLE
Build error on Ubuntu

### ISSUE THREAD

**Issue by glitsj16** [mmstick/systemd-manager#29]
Congrats with the v1.0.0, installs & runs fine on Arch Linux. On Ubuntu however, things error with the latest changes to Cargo.toml. cargo deb doesn't seem to like the '$auto' in the 'Depends' field:

$ cargo deb
unused manifest key: package.metadata.deb.assets
unused manifest key: package.metadata.deb.assets
unused manifest key: package.metadata.deb.assets
unused manifest key: package.metadata.deb.assets
unused manifest key: package.metadata.deb.assets
unused manifest key: package.metadata.deb.assets
unused manifest key: package.metadata.deb.assets
unused manifest key: package.metadata.deb.assets
unused manifest key: package.metadata.deb.assets
unused manifest key: package.metadata.deb.assets
unused manifest key: package.metadata.deb.assets
unused manifest key: package.metadata.deb.assets
unused manifest key: package.metadata.deb.copyright
unused manifest key: package.metadata.deb.depends
unused manifest key: package.metadata.deb.extended_description
unused manifest key: package.metadata.deb.license_file
unused manifest key: package.metadata.deb.license_file
unused manifest key: package.metadata.deb.maintainer
unused manifest key: package.metadata.deb.priority
unused manifest key: package.metadata.deb.section
   Compiling bitflags v0.5.0
   Compiling bitflags v0.4.0
   Compiling gio v0.1.0
   Compiling void v1.0.2
   Compiling gdk v0.5.0
   Compiling gtk v0.1.0
   Compiling libc v0.2.13
   Compiling pkg-config v0.3.8
   Compiling c_vec v1.0.12
   Compiling gdk-pixbuf v0.1.0
   Compiling glib-sys v0.3.1
   Compiling atk-sys v0.3.1
   Compiling gobject-sys v0.3.1
   Compiling gdk-sys v0.3.1
   Compiling dbus v0.3.4
   Compiling gtk-sys v0.3.1
   Compiling pango-sys v0.3.1
   Compiling num-traits v0.1.32
   Compiling unreachable v0.1.1
   Compiling quickersort v2.0.1
   Compiling cairo-sys-rs v0.3.1
   Compiling gdk-pixbuf-sys v0.3.1
   Compiling gio-sys v0.3.1
   Compiling cairo-rs v0.1.0
   Compiling glib v0.1.0
   Compiling pango v0.1.0
   Compiling systemd-manager v1.0.0 (file:///tmp/bz-dirkos/systemd-manager-git)
dpkg-deb: error: parsing file 'debian/DEBIAN/control' near line 8 package 'systemd-manager':
 'Depends' field, invalid package name '$auto': must start with an alphanumeric character
dpkg: error processing archive systemd-manager*.deb (--install):

After a manual $ sed -i -e "s/\$auto/libc6, libgtk-3-0 (>= 3.16)/" Cargo.toml the build works again.

**Comment by mmstick** [comment]
Ensure that you have the latest version of cargo-deb installed.

**Comment by glitsj16** [comment]
Turned out to be my own mistake. I made a custom script to build/update both cargo-deb & systemd-manager from git. Forgot that on Ubuntu the deb is dropped into target/debian instead of target/release.. Thanks for putting me in the right direction to solve things. Closing the non-issue.
