### ISSUE TITLE
Taskbar shows . dot on XFCE

### ISSUE THREAD

**Issue by linuxlite** [mmstick/systemd-manager#30]
Suggest taskbar item in XFCE shows title of application eg. SystemD Manager
Currently is shows just a dot.

![screenshot_2016-07-05_21-27-21](https://cloud.githubusercontent.com/assets/5382578/16580155/49302198-42f7-11e6-8291-8d114de0d8bb.png)

**Comment by daboross** [comment]
The window name is also shown as `.` when using i3.

**Comment by mmstick** [comment]
If anyone knows what causes this, that would be great. The title of the application should be set in the glade file, but I'm not able to get glade to fix this problem.
