### ISSUE TITLE
Build fails on 32bit 1.0.0- cargo-deb: failed to compress archive with xz

### ISSUE THREAD

**Issue by linuxlite** [mmstick/systemd-manager#31]
Had to install liblzma-dev also, worked on 64bit but not on 32bit.
32bit output:

```
jerry@jerry-VirtualBox:~$ git clone https://github.com/mmstick/systemd-manager
Cloning into 'systemd-manager'...
remote: Counting objects: 675, done.
remote: Total 675 (delta 0), reused 0 (delta 0), pack-reused 675
Receiving objects: 100% (675/675), 2.85 MiB | 557.00 KiB/s, done.
Resolving deltas: 100% (385/385), done.
Checking connectivity... done.
jerry@jerry-VirtualBox:~$ cd systemd-manager/
jerry@jerry-VirtualBox:~/systemd-manager$ cargo deb
warning: unused manifest key: package.metadata.deb.assets
warning: unused manifest key: package.metadata.deb.assets
warning: unused manifest key: package.metadata.deb.assets
warning: unused manifest key: package.metadata.deb.assets
warning: unused manifest key: package.metadata.deb.assets
warning: unused manifest key: package.metadata.deb.assets
warning: unused manifest key: package.metadata.deb.assets
warning: unused manifest key: package.metadata.deb.assets
warning: unused manifest key: package.metadata.deb.assets
warning: unused manifest key: package.metadata.deb.assets
warning: unused manifest key: package.metadata.deb.assets
warning: unused manifest key: package.metadata.deb.assets
warning: unused manifest key: package.metadata.deb.copyright
warning: unused manifest key: package.metadata.deb.depends
warning: unused manifest key: package.metadata.deb.extended_description
warning: unused manifest key: package.metadata.deb.license_file
warning: unused manifest key: package.metadata.deb.license_file
warning: unused manifest key: package.metadata.deb.maintainer
warning: unused manifest key: package.metadata.deb.priority
warning: unused manifest key: package.metadata.deb.section
   Compiling gdk-pixbuf v0.1.0
   Compiling c_vec v1.0.12
   Compiling num-traits v0.1.32
   Compiling cairo-rs v0.1.0
   Compiling libc v0.2.13
   Compiling gtk v0.1.0
   Compiling void v1.0.2
   Compiling gdk v0.5.0
   Compiling unreachable v0.1.1
   Compiling pkg-config v0.3.8
   Compiling bitflags v0.5.0
   Compiling bitflags v0.4.0
   Compiling gio v0.1.0
   Compiling gdk-sys v0.3.1
   Compiling gobject-sys v0.3.1
   Compiling atk-sys v0.3.1
   Compiling pango-sys v0.3.1
   Compiling cairo-sys-rs v0.3.1
   Compiling gtk-sys v0.3.1
   Compiling gdk-pixbuf-sys v0.3.1
   Compiling quickersort v2.0.1
   Compiling gio-sys v0.3.1
   Compiling glib-sys v0.3.1
   Compiling dbus v0.3.4
   Compiling glib v0.1.0
   Compiling pango v0.1.0
   Compiling systemd-manager v1.0.0 (file:///home/jerry/systemd-manager)
cargo-deb: failed to compress archive with xz: Unsupported compression options
error: third party subcommand `cargo-deb` exited unsuccessfully

To learn more, run the command again with --verbose.
jerry@jerry-VirtualBox:~/systemd-manager$ apt-cache policy liblzma-dev
liblzma-dev:
  Installed: 5.1.1alpha+20120614-2ubuntu2
  Candidate: 5.1.1alpha+20120614-2ubuntu2
  Version table:
 *** 5.1.1alpha+20120614-2ubuntu2 500
        500 http://nz.archive.ubuntu.com/ubuntu xenial/main i386 Packages
        100 /var/lib/dpkg/status
jerry@jerry-VirtualBox:~/systemd-manager$ 
```

**Comment by linuxlite** [comment]
Is development for this software still active?

**Comment by mmstick** [comment]
Sorry, I didn't see this issue. That would be an issue with the lzma crate I'm using in my cargo-deb application, which is a separate project, although I don't know what would be causing it to error on it.

**Comment by khurshid-alam** [comment]
Same issue here.

**Comment by mmstick** [comment]
The [fix](https://github.com/fpgaminer/rust-lzma/pull/12) for this was uploaded several months back, but it seems the maintainer of the `rust-lzma` crate has stopped maintaining it, so the pull request is in limbo.

**Comment by khurshid-alam** [comment]
Ok. So if I upload patched version of rust-lzma and then modify dependency to `rust-lzma = { git = "https://github.com/user/rust-lzma-patched" `} in cargo.toml, will it work?

**Comment by mmstick** [comment]
Yes, that would work.

**Comment by mmstick** [comment]
The cargo deb tool is no longer recommended as Debian provides their own packaging tools for Rust projects, so I am closing this.

**Comment by khurshid-alam** [comment]
Which package. Do you have any instruction to install without cargo deb?

**Comment by mmstick** [comment]
Well, you didn't need it to begin with. The instructions for other Linux
distributions apply to Ubuntu too. I've not used Debian's official tools,
so I don't know how they're used.

**Comment by khurshid-alam** [comment]
The instructions remained same from the beginning. So what's change? 

>The cargo deb tool is no longer recommended as Debian provides their own packaging tools for Rust projects....

Can you elaborate on this?

**Comment by mmstick** [comment]
@khurshid-alam 
> The instructions remained same from the beginning. So what's changed?

[The instructions are the same as before](https://github.com/mmstick/systemd-manager#everyone-else), just don't follow the Ubuntu-specific directions.

> Can you elaborate on this?

The announcement was made a long while back from the official Debian team committed to integrating Rust within the Debian ecosystem. They made `debcargo` and `dh-cargo' for this purpose.

**Comment by khurshid-alam** [comment]
> The instructions are the same as before, just don't follow the Ubuntu-specific directions.

It uses install section in makefile, i.e 

`install -Dm 755 target/release/systemd-manager "$(DESTDIR)/bin/systemd-manager" `

The systemd-manager binary compiled for 64 bit, hence it won't work for 32 bit.

>The announcement was made a long while back from the official Debian team committed to integrating Rust within the Debian ecosystem. They made debcargo and dh-cargo for this purpose.

Alright, I will look into it.

**Comment by mmstick** [comment]
It can't be compiled for 64-bit if you are building on a 32-bit platform. The default Rust target is your native platform's target.

**Comment by khurshid-alam** [comment]
All I need is a 32 bit binary for 32-bit platform. And for that you have to compile it, but as of now it's broken due to lzma issue. 

There isn't a problem with 64 bit in the first place. 64 bit works alright.

**Comment by mmstick** [comment]
It has always compiled just fine on 32-bit systems, so long as you don't
use cargo-deb. Basically, just don't follow the Ubuntu-specific
instructions.
