### ISSUE TITLE
Apache does not appear in the services list

### ISSUE THREAD

**Issue by saidbakr** [mmstick/systemd-manager#32]
I have installed deb package ver. 0.4.7 and the Apache does not be found in the services list. It is installed on Ubuntu 16.04 as virtual box.

**Comment by mmstick** [comment]
I'll add a binary package for 1.0.0 soon that you can try.

**Comment by saidbakr** [comment]
I hope that version 1.0.0 will has a deb package too.

**Comment by mmstick** [comment]
Just built this in an Ubuntu chroot on my Gentoo laptop:
https://github.com/mmstick/systemd-manager/releases/download/1.0.0/systemd-manager_1.0.0_amd64.deb

**Comment by mmstick** [comment]
Does this still happen?
