### ISSUE TITLE
When journal tab is updated it scrolls back to the top

### ISSUE THREAD

**Issue by pftbest** [mmstick/systemd-manager#42]
When some service has a lot of text in the journal tab, it is impossible to scroll to the bottom of text field because every couple of seconds it resets back to the top.

**Comment by mmstick** [comment]
Quick solution is to comment out [this line](https://github.com/mmstick/systemd-manager/blob/master/src/gui/gtk3/mod.rs#L206).

**Comment by mmstick** [comment]
I will be fixing this soon, so stay tuned.

**Comment by mmstick** [comment]
Solved
