### ISSUE TITLE
compilation error on linux mint 18.1

### ISSUE THREAD

**Issue by agricolamz** [mmstick/systemd-manager#44]
Compiling nodrop v0.1.9
warning: redundant linker flag specified for library `dbus-1`

   Compiling num-traits v0.1.37
   Compiling quickersort v2.2.0
   Compiling pango-sys v0.3.3
error: failed to run custom build command for `gdk-sys v0.3.3`
process didn't exit successfully: `/home/agricolamz/systemd-manager/target/release/build/gdk-sys-0b354205b232b6b0/build-script-build` (exit code: 1)
--- stderr
`"pkg-config" "--libs" "--cflags" "gdk-3.0 >= 3.16"` did not exit successfully: exit code: 1
--- stderr
Package gdk-3.0 was not found in the pkg-config search path.
Perhaps you should add the directory containing `gdk-3.0.pc'
to the PKG_CONFIG_PATH environment variable
No package 'gdk-3.0' found

Build failed, waiting for other jobs to finish...

error: build failed
Makefile:6: ошибка выполнения рецепта для цели «all»
make: *** [all] Ошибка 101

**Comment by daboross** [comment]
It looks like some of the development libraries (`gdk`) are missing. It doesn't seem documented which ones exactly systemd-manager requires for building, and I'm not sure what exact package has `gdk` headers, but I installing the `gnome-platform-devel` package should get you everything you need.

**Comment by agricolamz** [comment]
You are right. Thank you!

**Comment by siddht5** [comment]
@daboross  thanks for helping in compiling `gdk-sys v0.3.3`. Used `sudo apt install gnome-platform-devel` to fix the gdk issue. Also looks like this problem occurs across all ubuntu 16.04 derivatives (in my case LM 18.3)
