### ISSUE TITLE
App name is '.'

### ISSUE THREAD

**Issue by flipflop97** [mmstick/systemd-manager#47]
The running app has the name '.' instead of 'Systemd Manager'.

![image](https://user-images.githubusercontent.com/13943260/28490522-679aa3c6-6edc-11e7-992d-4659887180f7.png)

Arch Linux  
systemd-manager 1.0.0-1 (AUR)

**Comment by TomaszGasior** [comment]
It is also visible when user have patched version of GTK to disable CSDs. Window title contains "." instead of "systemd Manager"

**Comment by mmstick** [comment]
This was already fixed back in March: https://github.com/mmstick/systemd-manager/pull/41
