### ISSUE TITLE
Unexpected behaviour of sidebar scrollbar

### ISSUE THREAD

**Issue by TomaszGasior** [mmstick/systemd-manager#49]
It seems to me that systemd-manager uses some kind of dirty hack in scrollbar of left sidebar. See screenshots.

When I have GTK_OVERLAY_SCROLLING=1 (default in GNOME).
https://i.imgur.com/Iz9LDHs.png

When I have GTK_OVERLAY_SCROLLING=0 (default in MATE, often used in XFCE).
https://i.imgur.com/rbYLFTp.png
Second icon in sidebar row is not fully visible. It's not readable. 

Problem exists in each theme, on screenshot Adwaita theme is visible.

**Comment by mmstick** [comment]
No hacks are employed here. Just that there is no padding being performed as a workaround for those still using the ancient behavior.

**Comment by TomaszGasior** [comment]
Why did you closed this issue while problem still exists? It is hard to read current state of service from list if user disabled GTK's overlay scrolling.

![przechwycenie obrazu ekranu_2017-12-01_13-10-33](https://user-images.githubusercontent.com/1395027/33486179-61827628-d6a9-11e7-9a42-15f093718af4.png)

**Comment by mmstick** [comment]
This project is being rewritten from scratch. All issues will be closed in the next day or so.

**Comment by TomaszGasior** [comment]
Ok, understand.
