### ISSUE TITLE
Scrollbar blocks enabled/disabled icons

### ISSUE THREAD

**Issue by daboross** [mmstick/systemd-manager#5]
Awesome program, by the way!

I just was wondering if this was in issue with the program, or my local gtk theme/setup:

![screenshot](http://i.imgur.com/YczDiwW.png)

The scrollbar does disappear, but it does also block the view whenever the mouse is moved in that area. Is this intentional, an issue with my setup, or a bug?

**Comment by mmstick** [comment]
Which version of GTK are you using? None of the themes I've tried (Adwaita, Adapta, Arc) exhibit the behaviour, but I can increase the amount of spacing so that you won't have that problem.

**Comment by mmstick** [comment]
I've just pushed a commit that should resolve your problem for you, so check back with me if it is fixed.

**Comment by daboross** [comment]
Awesome, will do! I'm using version 3.18 with the Numix light theme.

**Comment by mmstick** [comment]
I'm using GTK 3.20 on Arch Linux with the Adapta theme primarily. Essentially, my scrollbar stays relatively hidden (maybe 3 px wide), and when it does appear, it's much thinner than shown in your screenshot (around 6px). I'm sure the extra 10px padding I've added to the left pane is fine.

You may also be interested in testing out my other GTK3-based Rust application, [TV Renamer](https://github.com/mmstick/tv-renamer).
