### ISSUE TITLE
systemd-manager for ubuntu

### ISSUE THREAD

**Issue by drizzersilverberg** [mmstick/systemd-manager#57]
is this available for Ubuntu 16.04 or above? And how the easiest way to install this package in ubuntu?

**Comment by mmstick** [comment]
The rewrite is on hold at the moment. Now that I'm working at System76, their project come first.

**Comment by pszalanski** [comment]
In the meantime, I can tell you what I did, to get it to compile.

First, I needed a couple of packages, including `rustc` and `cargo`:

```bash
$ sudo apt install pkg-config libdbus-1-dev libgtk-3-dev rustc cargo
... [installing loads of dependencies]
$ 
```

After that, I just cloned the repo and built it using `make`, just like the instructions specify.

**Comment by khurshid-alam** [comment]
@pszalanski 

For me it didn't work. As it depends on libmirclient which was removed from the archive. Are you using master branch to compile ?

**Comment by mati865** [comment]
@khurshid-alam on Ubuntu 18.04 branch `rewrite` builds fine.

**Comment by khurshid-alam** [comment]
@mati865 For me it doesn't. How are you installing? For me `cargo build` doesn't work.

**Comment by mati865** [comment]
@khurshid-alam `cargo build --release`, you are either missing dependencies or messed up your system.
You need to provide log with the error and your system details (e.g. output of `cat /etc/os-release`).

**Comment by khurshid-alam** [comment]
@mati865 I am missing dependencies. Same with `sudo make install`. :(

**Comment by khurshid-alam** [comment]
@mati865 

Travis build also fails from rewrite branch. https://travis-ci.org/mmstick/systemd-manager/builds/314529333

**Comment by mati865** [comment]
@khurshid-alam Travis does use Ubuntu 14.04 which is too old. This package builds fine after you install **all** dependencies.
