### ISSUE TITLE
Unit file pane does not update when switching filters.

### ISSUE THREAD

**Issue by snake66** [mmstick/systemd-manager#7]
To reproduce:
1. Select one of the filters, say "services".
2. Click on one of the services to view it's unit file.
3. Select another filter, say "timers".
4. Click on one of the timers to view it's unit file.
5. Select same filter as in step 1.

The service that was selected in step 2 is still hightlighted, but the unit file from the unit selected in step 4 is still showing in the unit file pane.

**Comment by mmstick** [comment]
I will fix this shortly. It should only be about three lines of code to solve.

**Comment by snake66** [comment]
That's what I thought. Just wanted to let you know :)

**Comment by mmstick** [comment]
Your issue should be fixed now. If it is, you can close this issue.

**Comment by snake66** [comment]
Beautiful! :)
